[test]
levels = ["syntax", "install", "javascript", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
cpu = ['apply_animation','skeleton_comparison','rigged_manipulator']
cuda = ["mia_humanoid","unirig_bird","unirig_humanoid"]

[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable", "macos_desktop", "windows_desktop", "linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]
